import type { QuranTranslationId } from "@/hifzer/quran/translation-prefs";

export type ReaderUiCopy = {
  back: string;
  quranReaderPill: string;
  heroTitle: string;
  heroSubtitle: string;
  readerFilters: string;
  show: string;
  hide: string;
  trackingOn: string;
  anonymousWindow: string;
  listView: string;
  compactView: string;
  enablePhonetics: string;
  disablePhonetics: string;
  enableTranslation: string;
  disableTranslation: string;
  surah: string;
  allSurahs: string;
  ayahGlobalId: string;
  ayahPlaceholder: string;
  applyFilters: string;
  clear: string;
  ayahsMatchedSuffix: string;
  anonymousMode: string;
  trackingMode: string;
  language: string;
  phoneticsOn: string;
  phoneticsOff: string;
  translationOn: string;
  translationOff: string;
  showing: string;
  surahLabel: string;
  ayahLabel: string;
  noResults: string;
  noResultsMessage: string;
  clearAllFilters: string;
  phoneticUnavailable: string;
  translationUnavailable: string;
  detailsHiddenInFilters: string;
  previousPage: string;
  nextPage: string;
  page: string;
  of: string;
  previous: string;
  next: string;
  nextSurah: string;
  translationLanguage: string;
  active: string;
  defaultDetails: string;
  visible: string;
  hidden: string;
  hideDetails: string;
  showDetails: string;
  defaultDetailsHint: string;
  signInToPersist: string;
  savedTitle: string;
  saveFailedTitle: string;
  translationLanguageUpdated: string;
  readerDetailsEnabled: string;
  readerDetailsHidden: string;
  failedSaveLanguage: string;
  failedSaveReaderPreferences: string;
  persistenceUnavailable: string;
  saveIssue: string;
};

const READER_UI_COPY: Record<QuranTranslationId, ReaderUiCopy> = {
  "en.sahih": {
    back: "Back",
    quranReaderPill: "Qur'an Reader",
    heroTitle: "Recite the Qur'an. It will intercede for you.",
    heroSubtitle: "Return daily, and let every ayah become your witness.",
    readerFilters: "Reader filters",
    show: "Show",
    hide: "Hide",
    trackingOn: "Tracking on",
    anonymousWindow: "Anonymous window",
    listView: "List view",
    compactView: "Compact view",
    enablePhonetics: "Enable phonetics",
    disablePhonetics: "Disable phonetics",
    enableTranslation: "Enable translation",
    disableTranslation: "Disable translation",
    surah: "Surah",
    allSurahs: "All surahs",
    ayahGlobalId: "Ayah (global id)",
    ayahPlaceholder: "1 - 6236",
    applyFilters: "Apply filters",
    clear: "Clear",
    ayahsMatchedSuffix: "ayahs matched",
    anonymousMode: "Anonymous mode",
    trackingMode: "Tracking mode",
    language: "Language",
    phoneticsOn: "Phonetics on",
    phoneticsOff: "Phonetics off",
    translationOn: "Translation on",
    translationOff: "Translation off",
    showing: "Showing",
    surahLabel: "Surah",
    ayahLabel: "Ayah",
    noResults: "No results",
    noResultsMessage: "No ayahs matched this filter combination. Try clearing one or more filters.",
    clearAllFilters: "Clear all filters",
    phoneticUnavailable: "Phonetic unavailable",
    translationUnavailable: "Translation unavailable",
    detailsHiddenInFilters: "Phonetics and translation are hidden in reader filters.",
    previousPage: "Previous page",
    nextPage: "Next page",
    page: "Page",
    of: "of",
    previous: "Previous",
    next: "Next",
    nextSurah: "Next Surah",
    translationLanguage: "Translation language",
    active: "Active",
    defaultDetails: "Default details",
    visible: "Visible",
    hidden: "Hidden",
    hideDetails: "Hide details",
    showDetails: "Show details",
    defaultDetailsHint: "Sets the default for phonetics and translation. Reader filter toggles can override this view.",
    signInToPersist: "Sign in to persist reader preferences.",
    savedTitle: "Saved",
    saveFailedTitle: "Save failed",
    translationLanguageUpdated: "Translation language updated.",
    readerDetailsEnabled: "Reader details enabled.",
    readerDetailsHidden: "Reader details hidden.",
    failedSaveLanguage: "Failed to save language preference.",
    failedSaveReaderPreferences: "Failed to save reader preferences.",
    persistenceUnavailable: "Persistence unavailable",
    saveIssue: "Save issue",
  },
  "ur.junagarhi": {
    back: "واپس",
    quranReaderPill: "قرآن ریڈر",
    heroTitle: "قرآن کی تلاوت کریں۔ یہ آپ کی شفاعت کرے گا۔",
    heroSubtitle: "روزانہ واپس آئیں، اور ہر آیت کو اپنا گواہ بنائیں۔",
    readerFilters: "ریڈر فلٹرز",
    show: "دکھائیں",
    hide: "چھپائیں",
    trackingOn: "ٹریکنگ آن",
    anonymousWindow: "گمنام ونڈو",
    listView: "فہرست منظر",
    compactView: "کمپیکٹ منظر",
    enablePhonetics: "فونیٹکس فعال کریں",
    disablePhonetics: "فونیٹکس غیر فعال کریں",
    enableTranslation: "ترجمہ فعال کریں",
    disableTranslation: "ترجمہ غیر فعال کریں",
    surah: "سورہ",
    allSurahs: "تمام سورتیں",
    ayahGlobalId: "آیت (عالمی آئی ڈی)",
    ayahPlaceholder: "1 - 6236",
    applyFilters: "فلٹرز لاگو کریں",
    clear: "صاف کریں",
    ayahsMatchedSuffix: "آیات ملیں",
    anonymousMode: "گمنام موڈ",
    trackingMode: "ٹریکنگ موڈ",
    language: "زبان",
    phoneticsOn: "فونیٹکس آن",
    phoneticsOff: "فونیٹکس آف",
    translationOn: "ترجمہ آن",
    translationOff: "ترجمہ آف",
    showing: "دکھایا جا رہا ہے",
    surahLabel: "سورہ",
    ayahLabel: "آیت",
    noResults: "کوئی نتیجہ نہیں",
    noResultsMessage: "اس فلٹر امتزاج سے کوئی آیت نہیں ملی۔ ایک یا زیادہ فلٹر صاف کریں۔",
    clearAllFilters: "تمام فلٹر صاف کریں",
    phoneticUnavailable: "فونیٹکس دستیاب نہیں",
    translationUnavailable: "ترجمہ دستیاب نہیں",
    detailsHiddenInFilters: "فونیٹکس اور ترجمہ ریڈر فلٹرز میں چھپے ہوئے ہیں۔",
    previousPage: "پچھلا صفحہ",
    nextPage: "اگلا صفحہ",
    page: "صفحہ",
    of: "از",
    previous: "پچھلا",
    next: "اگلا",
    nextSurah: "اگلی سورہ",
    translationLanguage: "ترجمہ کی زبان",
    active: "فعال",
    defaultDetails: "ڈیفالٹ تفصیلات",
    visible: "مرئی",
    hidden: "مخفی",
    hideDetails: "تفصیلات چھپائیں",
    showDetails: "تفصیلات دکھائیں",
    defaultDetailsHint: "یہ فونیٹکس اور ترجمہ کی ڈیفالٹ ترتیب طے کرتا ہے۔ ریڈر فلٹرز اسے عارضی طور پر بدل سکتے ہیں۔",
    signInToPersist: "ترجیحات محفوظ کرنے کے لیے سائن اِن کریں۔",
    savedTitle: "محفوظ",
    saveFailedTitle: "محفوظ نہیں ہو سکا",
    translationLanguageUpdated: "ترجمہ کی زبان اپڈیٹ ہو گئی۔",
    readerDetailsEnabled: "ریڈر تفصیلات فعال ہو گئیں۔",
    readerDetailsHidden: "ریڈر تفصیلات چھپا دی گئیں۔",
    failedSaveLanguage: "زبان کی ترجیح محفوظ نہ ہو سکی۔",
    failedSaveReaderPreferences: "ریڈر ترجیحات محفوظ نہ ہو سکیں۔",
    persistenceUnavailable: "پرسسٹنس دستیاب نہیں",
    saveIssue: "محفوظ کرنے کا مسئلہ",
  },
  "id.indonesian": {
    back: "Kembali",
    quranReaderPill: "Pembaca Al-Qur'an",
    heroTitle: "Bacalah Al-Qur'an. Ia akan memberi syafaat bagimu.",
    heroSubtitle: "Kembali setiap hari, dan jadikan setiap ayat sebagai saksimu.",
    readerFilters: "Filter pembaca",
    show: "Tampilkan",
    hide: "Sembunyikan",
    trackingOn: "Pelacakan aktif",
    anonymousWindow: "Jendela anonim",
    listView: "Tampilan daftar",
    compactView: "Tampilan ringkas",
    enablePhonetics: "Aktifkan fonetik",
    disablePhonetics: "Nonaktifkan fonetik",
    enableTranslation: "Aktifkan terjemahan",
    disableTranslation: "Nonaktifkan terjemahan",
    surah: "Surah",
    allSurahs: "Semua surah",
    ayahGlobalId: "Ayat (ID global)",
    ayahPlaceholder: "1 - 6236",
    applyFilters: "Terapkan filter",
    clear: "Bersihkan",
    ayahsMatchedSuffix: "ayat cocok",
    anonymousMode: "Mode anonim",
    trackingMode: "Mode pelacakan",
    language: "Bahasa",
    phoneticsOn: "Fonetik aktif",
    phoneticsOff: "Fonetik nonaktif",
    translationOn: "Terjemahan aktif",
    translationOff: "Terjemahan nonaktif",
    showing: "Menampilkan",
    surahLabel: "Surah",
    ayahLabel: "Ayat",
    noResults: "Tidak ada hasil",
    noResultsMessage: "Tidak ada ayat yang cocok dengan kombinasi filter ini. Coba bersihkan satu atau lebih filter.",
    clearAllFilters: "Bersihkan semua filter",
    phoneticUnavailable: "Fonetik tidak tersedia",
    translationUnavailable: "Terjemahan tidak tersedia",
    detailsHiddenInFilters: "Fonetik dan terjemahan disembunyikan di filter pembaca.",
    previousPage: "Halaman sebelumnya",
    nextPage: "Halaman berikutnya",
    page: "Halaman",
    of: "dari",
    previous: "Sebelumnya",
    next: "Berikutnya",
    nextSurah: "Surah berikutnya",
    translationLanguage: "Bahasa terjemahan",
    active: "Aktif",
    defaultDetails: "Detail bawaan",
    visible: "Terlihat",
    hidden: "Tersembunyi",
    hideDetails: "Sembunyikan detail",
    showDetails: "Tampilkan detail",
    defaultDetailsHint: "Mengatur bawaan fonetik dan terjemahan. Toggle filter pembaca dapat menimpanya.",
    signInToPersist: "Masuk untuk menyimpan preferensi pembaca.",
    savedTitle: "Tersimpan",
    saveFailedTitle: "Gagal menyimpan",
    translationLanguageUpdated: "Bahasa terjemahan diperbarui.",
    readerDetailsEnabled: "Detail pembaca diaktifkan.",
    readerDetailsHidden: "Detail pembaca disembunyikan.",
    failedSaveLanguage: "Gagal menyimpan preferensi bahasa.",
    failedSaveReaderPreferences: "Gagal menyimpan preferensi pembaca.",
    persistenceUnavailable: "Persistensi tidak tersedia",
    saveIssue: "Masalah penyimpanan",
  },
  "tr.yildirim": {
    back: "Geri",
    quranReaderPill: "Kur'an Okuyucu",
    heroTitle: "Kur'an okuyun. O size şefaat edecektir.",
    heroSubtitle: "Her gün geri dönün ve her ayet şahidiniz olsun.",
    readerFilters: "Okuyucu filtreleri",
    show: "Göster",
    hide: "Gizle",
    trackingOn: "Takip açık",
    anonymousWindow: "Anonim pencere",
    listView: "Liste görünümü",
    compactView: "Kompakt görünüm",
    enablePhonetics: "Fonetiği aç",
    disablePhonetics: "Fonetiği kapat",
    enableTranslation: "Çeviriyi aç",
    disableTranslation: "Çeviriyi kapat",
    surah: "Sure",
    allSurahs: "Tüm sureler",
    ayahGlobalId: "Ayet (genel kimlik)",
    ayahPlaceholder: "1 - 6236",
    applyFilters: "Filtreleri uygula",
    clear: "Temizle",
    ayahsMatchedSuffix: "ayet eşleşti",
    anonymousMode: "Anonim mod",
    trackingMode: "Takip modu",
    language: "Dil",
    phoneticsOn: "Fonetik açık",
    phoneticsOff: "Fonetik kapalı",
    translationOn: "Çeviri açık",
    translationOff: "Çeviri kapalı",
    showing: "Gösterilen",
    surahLabel: "Sure",
    ayahLabel: "Ayet",
    noResults: "Sonuç yok",
    noResultsMessage: "Bu filtre kombinasyonu için ayet bulunamadı. Bir veya daha fazla filtreyi temizleyin.",
    clearAllFilters: "Tüm filtreleri temizle",
    phoneticUnavailable: "Fonetik mevcut değil",
    translationUnavailable: "Çeviri mevcut değil",
    detailsHiddenInFilters: "Fonetik ve çeviri okuyucu filtrelerinde gizli.",
    previousPage: "Önceki sayfa",
    nextPage: "Sonraki sayfa",
    page: "Sayfa",
    of: "/",
    previous: "Önceki",
    next: "Sonraki",
    nextSurah: "Sonraki sure",
    translationLanguage: "Çeviri dili",
    active: "Aktif",
    defaultDetails: "Varsayılan ayrıntılar",
    visible: "Görünür",
    hidden: "Gizli",
    hideDetails: "Ayrıntıları gizle",
    showDetails: "Ayrıntıları göster",
    defaultDetailsHint: "Fonetik ve çeviri için varsayılanı ayarlar. Okuyucu filtre anahtarları bunu geçersiz kılabilir.",
    signInToPersist: "Okuyucu tercihlerini kaydetmek için giriş yapın.",
    savedTitle: "Kaydedildi",
    saveFailedTitle: "Kaydetme başarısız",
    translationLanguageUpdated: "Çeviri dili güncellendi.",
    readerDetailsEnabled: "Okuyucu ayrıntıları açıldı.",
    readerDetailsHidden: "Okuyucu ayrıntıları gizlendi.",
    failedSaveLanguage: "Dil tercihi kaydedilemedi.",
    failedSaveReaderPreferences: "Okuyucu tercihleri kaydedilemedi.",
    persistenceUnavailable: "Kalıcılık kullanılamıyor",
    saveIssue: "Kaydetme sorunu",
  },
  "fa.fooladvand": {
    back: "بازگشت",
    quranReaderPill: "قرآن‌خوان",
    heroTitle: "قرآن بخوانید. برای شما شفاعت خواهد کرد.",
    heroSubtitle: "هر روز برگردید و بگذارید هر آیه گواه شما باشد.",
    readerFilters: "فیلترهای خواندن",
    show: "نمایش",
    hide: "پنهان",
    trackingOn: "رهگیری روشن",
    anonymousWindow: "پنجره ناشناس",
    listView: "نمای فهرست",
    compactView: "نمای فشرده",
    enablePhonetics: "آوانویسی را فعال کن",
    disablePhonetics: "آوانویسی را غیرفعال کن",
    enableTranslation: "ترجمه را فعال کن",
    disableTranslation: "ترجمه را غیرفعال کن",
    surah: "سوره",
    allSurahs: "همه سوره‌ها",
    ayahGlobalId: "آیه (شناسه سراسری)",
    ayahPlaceholder: "1 - 6236",
    applyFilters: "اعمال فیلترها",
    clear: "پاک‌کردن",
    ayahsMatchedSuffix: "آیه یافت شد",
    anonymousMode: "حالت ناشناس",
    trackingMode: "حالت رهگیری",
    language: "زبان",
    phoneticsOn: "آوانویسی روشن",
    phoneticsOff: "آوانویسی خاموش",
    translationOn: "ترجمه روشن",
    translationOff: "ترجمه خاموش",
    showing: "نمایش",
    surahLabel: "سوره",
    ayahLabel: "آیه",
    noResults: "نتیجه‌ای یافت نشد",
    noResultsMessage: "با این ترکیب فیلتر آیه‌ای پیدا نشد. یک یا چند فیلتر را پاک کنید.",
    clearAllFilters: "پاک‌کردن همه فیلترها",
    phoneticUnavailable: "آوانویسی موجود نیست",
    translationUnavailable: "ترجمه موجود نیست",
    detailsHiddenInFilters: "آوانویسی و ترجمه در فیلترهای خواندن پنهان هستند.",
    previousPage: "صفحه قبل",
    nextPage: "صفحه بعد",
    page: "صفحه",
    of: "از",
    previous: "قبلی",
    next: "بعدی",
    nextSurah: "سوره بعد",
    translationLanguage: "زبان ترجمه",
    active: "فعال",
    defaultDetails: "جزئیات پیش‌فرض",
    visible: "قابل‌نمایش",
    hidden: "پنهان",
    hideDetails: "پنهان‌کردن جزئیات",
    showDetails: "نمایش جزئیات",
    defaultDetailsHint: "پیش‌فرض آوانویسی و ترجمه را تنظیم می‌کند. فیلترهای خواندن می‌توانند آن را موقتاً تغییر دهند.",
    signInToPersist: "برای ذخیره ترجیحات وارد شوید.",
    savedTitle: "ذخیره شد",
    saveFailedTitle: "ذخیره ناموفق",
    translationLanguageUpdated: "زبان ترجمه به‌روزرسانی شد.",
    readerDetailsEnabled: "جزئیات خواندن فعال شد.",
    readerDetailsHidden: "جزئیات خواندن پنهان شد.",
    failedSaveLanguage: "ذخیره ترجیح زبان انجام نشد.",
    failedSaveReaderPreferences: "ذخیره ترجیحات خواندن انجام نشد.",
    persistenceUnavailable: "ذخیره‌سازی در دسترس نیست",
    saveIssue: "مشکل در ذخیره‌سازی",
  },
  "bn.bengali": {
    back: "ফিরে যান",
    quranReaderPill: "কুরআন রিডার",
    heroTitle: "কুরআন তিলাওয়াত করুন। এটি আপনার জন্য সুপারিশ করবে।",
    heroSubtitle: "প্রতিদিন ফিরে আসুন, এবং প্রতিটি আয়াতকে আপনার সাক্ষী হতে দিন।",
    readerFilters: "রিডার ফিল্টার",
    show: "দেখান",
    hide: "লুকান",
    trackingOn: "ট্র্যাকিং চালু",
    anonymousWindow: "অ্যানোনিমাস উইন্ডো",
    listView: "তালিকা ভিউ",
    compactView: "কমপ্যাক্ট ভিউ",
    enablePhonetics: "ফোনেটিক চালু করুন",
    disablePhonetics: "ফোনেটিক বন্ধ করুন",
    enableTranslation: "অনুবাদ চালু করুন",
    disableTranslation: "অনুবাদ বন্ধ করুন",
    surah: "সূরা",
    allSurahs: "সব সূরা",
    ayahGlobalId: "আয়াত (গ্লোবাল আইডি)",
    ayahPlaceholder: "1 - 6236",
    applyFilters: "ফিল্টার প্রয়োগ করুন",
    clear: "পরিষ্কার",
    ayahsMatchedSuffix: "টি আয়াত মিলেছে",
    anonymousMode: "অ্যানোনিমাস মোড",
    trackingMode: "ট্র্যাকিং মোড",
    language: "ভাষা",
    phoneticsOn: "ফোনেটিক চালু",
    phoneticsOff: "ফোনেটিক বন্ধ",
    translationOn: "অনুবাদ চালু",
    translationOff: "অনুবাদ বন্ধ",
    showing: "দেখানো হচ্ছে",
    surahLabel: "সূরা",
    ayahLabel: "আয়াত",
    noResults: "কোনো ফলাফল নেই",
    noResultsMessage: "এই ফিল্টার সমন্বয়ে কোনো আয়াত মেলেনি। এক বা একাধিক ফিল্টার পরিষ্কার করুন।",
    clearAllFilters: "সব ফিল্টার পরিষ্কার করুন",
    phoneticUnavailable: "ফোনেটিক পাওয়া যায়নি",
    translationUnavailable: "অনুবাদ পাওয়া যায়নি",
    detailsHiddenInFilters: "রিডার ফিল্টারে ফোনেটিক ও অনুবাদ লুকানো আছে।",
    previousPage: "আগের পৃষ্ঠা",
    nextPage: "পরের পৃষ্ঠা",
    page: "পৃষ্ঠা",
    of: "/",
    previous: "আগের",
    next: "পরের",
    nextSurah: "পরের সূরা",
    translationLanguage: "অনুবাদের ভাষা",
    active: "সক্রিয়",
    defaultDetails: "ডিফল্ট বিস্তারিত",
    visible: "দৃশ্যমান",
    hidden: "লুকানো",
    hideDetails: "বিস্তারিত লুকান",
    showDetails: "বিস্তারিত দেখান",
    defaultDetailsHint: "এটি ফোনেটিক ও অনুবাদের ডিফল্ট নির্ধারণ করে। রিডার ফিল্টার টগল এটি পরিবর্তন করতে পারে।",
    signInToPersist: "রিডার পছন্দ সংরক্ষণ করতে সাইন ইন করুন।",
    savedTitle: "সংরক্ষিত",
    saveFailedTitle: "সংরক্ষণ ব্যর্থ",
    translationLanguageUpdated: "অনুবাদের ভাষা আপডেট হয়েছে।",
    readerDetailsEnabled: "রিডার বিস্তারিত চালু হয়েছে।",
    readerDetailsHidden: "রিডার বিস্তারিত লুকানো হয়েছে।",
    failedSaveLanguage: "ভাষার পছন্দ সংরক্ষণ করা যায়নি।",
    failedSaveReaderPreferences: "রিডার পছন্দ সংরক্ষণ করা যায়নি।",
    persistenceUnavailable: "সংরক্ষণ সুবিধা উপলব্ধ নয়",
    saveIssue: "সংরক্ষণ সমস্যা",
  },
  "ml.abdulhameed": {
    back: "തിരികെ",
    quranReaderPill: "ഖുർആൻ റീഡർ",
    heroTitle: "ഖുർആൻ പാരായണം ചെയ്യൂ. അത് നിങ്ങൾക്കായി ശുപാർശ ചെയ്യും.",
    heroSubtitle: "ദിവസവും മടങ്ങിവരൂ; ഓരോ ആയത്തും നിങ്ങളുടെ സാക്ഷിയാകട്ടെ.",
    readerFilters: "റീഡർ ഫിൽറ്ററുകൾ",
    show: "കാണിക്കുക",
    hide: "മറയ്ക്കുക",
    trackingOn: "ട്രാക്കിംഗ് ഓൺ",
    anonymousWindow: "അനോനിമസ് വിൻഡോ",
    listView: "ലിസ്റ്റ് കാഴ്ച",
    compactView: "കംപാക്റ്റ് കാഴ്ച",
    enablePhonetics: "ഫോനറ്റിക് പ്രവർത്തനക്ഷമമാക്കുക",
    disablePhonetics: "ഫോനറ്റിക് പ്രവർത്തനരഹിതമാക്കുക",
    enableTranslation: "വിവർത്തനം പ്രവർത്തനക്ഷമമാക്കുക",
    disableTranslation: "വിവർത്തനം പ്രവർത്തനരഹിതമാക്കുക",
    surah: "സൂറ",
    allSurahs: "എല്ലാ സൂറകളും",
    ayahGlobalId: "ആയത്ത് (ഗ്ലോബൽ ഐഡി)",
    ayahPlaceholder: "1 - 6236",
    applyFilters: "ഫിൽറ്ററുകൾ പ്രയോഗിക്കുക",
    clear: "മായ്ക്കുക",
    ayahsMatchedSuffix: "ആയത്തുകൾ കണ്ടെത്തി",
    anonymousMode: "അനോനിമസ് മോഡ്",
    trackingMode: "ട്രാക്കിംഗ് മോഡ്",
    language: "ഭാഷ",
    phoneticsOn: "ഫോനറ്റിക് ഓൺ",
    phoneticsOff: "ഫോനറ്റിക് ഓഫ്",
    translationOn: "വിവർത്തനം ഓൺ",
    translationOff: "വിവർത്തനം ഓഫ്",
    showing: "കാണിക്കുന്നത്",
    surahLabel: "സൂറ",
    ayahLabel: "ആയത്ത്",
    noResults: "ഫലം ഇല്ല",
    noResultsMessage: "ഈ ഫിൽറ്റർ സംയോജനത്തിന് യോജിക്കുന്ന ആയത്തുകളൊന്നുമില്ല. ഒരു അല്ലെങ്കിൽ കൂടുതൽ ഫിൽറ്ററുകൾ മായ്ക്കുക.",
    clearAllFilters: "എല്ലാ ഫിൽറ്ററുകളും മായ്ക്കുക",
    phoneticUnavailable: "ഫോനറ്റിക് ലഭ്യമല്ല",
    translationUnavailable: "വിവർത്തനം ലഭ്യമല്ല",
    detailsHiddenInFilters: "റീഡർ ഫിൽറ്ററുകളിൽ ഫോനറ്റിക്കും വിവർത്തനവും മറച്ചിരിക്കുന്നു.",
    previousPage: "മുൻ പേജ്",
    nextPage: "അടുത്ത പേജ്",
    page: "പേജ്",
    of: "/",
    previous: "മുൻപ്",
    next: "അടുത്തത്",
    nextSurah: "അടുത്ത സൂറ",
    translationLanguage: "വിവർത്തന ഭാഷ",
    active: "സജീവം",
    defaultDetails: "ഡീഫോൾട്ട് വിശദാംശങ്ങൾ",
    visible: "ദൃശ്യം",
    hidden: "മറച്ചത്",
    hideDetails: "വിശദാംശങ്ങൾ മറയ്ക്കുക",
    showDetails: "വിശദാംശങ്ങൾ കാണിക്കുക",
    defaultDetailsHint: "ഫോനറ്റിക്കും വിവർത്തനത്തിനും ഡീഫോൾട്ട് ക്രമീകരിക്കുന്നു. റീഡർ ഫിൽറ്റർ ടോഗിളുകൾ ഇത് മാറ്റാം.",
    signInToPersist: "റീഡർ മുൻഗണനകൾ സംരക്ഷിക്കാൻ സൈൻ ഇൻ ചെയ്യുക.",
    savedTitle: "സംരക്ഷിച്ചു",
    saveFailedTitle: "സംരക്ഷിക്കൽ പരാജയപ്പെട്ടു",
    translationLanguageUpdated: "വിവർത്തന ഭാഷ പുതുക്കി.",
    readerDetailsEnabled: "റീഡർ വിശദാംശങ്ങൾ പ്രവർത്തനക്ഷമമാക്കി.",
    readerDetailsHidden: "റീഡർ വിശദാംശങ്ങൾ മറച്ചു.",
    failedSaveLanguage: "ഭാഷാ മുൻഗണന സംരക്ഷിക്കാൻ കഴിഞ്ഞില്ല.",
    failedSaveReaderPreferences: "റീഡർ മുൻഗണനകൾ സംരക്ഷിക്കാൻ കഴിഞ്ഞില്ല.",
    persistenceUnavailable: "സ്ഥിരസംഭരണം ലഭ്യമല്ല",
    saveIssue: "സംരക്ഷിക്കൽ പ്രശ്നം",
  },
};

export function getReaderUiCopy(translationId: QuranTranslationId): ReaderUiCopy {
  return READER_UI_COPY[translationId];
}
