import type { DemoData } from "./types";

export const DEMO: DemoData = {
  users: [
    {
      id: "user_am",
      name: "Amina Rahman",
      email: "amina@kitewave.demo",
      memberId: "mem_am",
      teamIds: ["team_northstar", "team_orbit", "team_harbor"],
      defaultTeamId: "team_northstar",
    },
    {
      id: "user_mc",
      name: "Marcus Chen",
      email: "marcus@kitewave.demo",
      memberId: "mem_mc",
      teamIds: ["team_northstar", "team_harbor"],
      defaultTeamId: "team_harbor",
    },
    {
      id: "user_si",
      name: "Sofia Ibarra",
      email: "sofia@kitewave.demo",
      memberId: "mem_si",
      teamIds: ["team_orbit", "team_northstar"],
      defaultTeamId: "team_orbit",
    },
  ],
  teams: [
    {
      id: "team_northstar",
      name: "Northstar Ops",
      handle: "northstar",
      tagline: "Execution with signal.",
      brand: { primary: "#0a8a77", accent: "#2b4bff" },
      memberIds: ["mem_am", "mem_si", "mem_jo", "mem_kl", "mem_ad"],
    },
    {
      id: "team_orbit",
      name: "Orbit Growth",
      handle: "orbit",
      tagline: "Make the funnel sing.",
      brand: { primary: "#2b4bff", accent: "#ea580c" },
      memberIds: ["mem_am", "mem_si", "mem_rn", "mem_ys", "mem_tm"],
    },
    {
      id: "team_harbor",
      name: "Harbor Platform",
      handle: "harbor",
      tagline: "A calm backbone for fast teams.",
      brand: { primary: "#ea580c", accent: "#0a8a77" },
      memberIds: ["mem_mc", "mem_ad", "mem_kl", "mem_jp", "mem_ys"],
    },
  ],
  members: [
    {
      id: "mem_am",
      name: "Amina Rahman",
      title: "Product Lead",
      role: "Admin",
      timezone: "America/Los_Angeles",
      avatarSeed: "am",
    },
    {
      id: "mem_mc",
      name: "Marcus Chen",
      title: "Engineering Lead",
      role: "Lead",
      timezone: "America/New_York",
      avatarSeed: "mc",
    },
    {
      id: "mem_si",
      name: "Sofia Ibarra",
      title: "Design Director",
      role: "Lead",
      timezone: "Europe/London",
      avatarSeed: "si",
    },
    {
      id: "mem_kl",
      name: "Kaito Lee",
      title: "Staff Engineer",
      role: "Member",
      timezone: "Asia/Tokyo",
      avatarSeed: "kl",
    },
    {
      id: "mem_ad",
      name: "Avery Davis",
      title: "QA / Reliability",
      role: "Member",
      timezone: "America/Chicago",
      avatarSeed: "ad",
    },
    {
      id: "mem_jo",
      name: "Jules Ortega",
      title: "Operations Analyst",
      role: "Member",
      timezone: "America/Denver",
      avatarSeed: "jo",
    },
    {
      id: "mem_rn",
      name: "Rina Nakamura",
      title: "Growth PM",
      role: "Lead",
      timezone: "Asia/Singapore",
      avatarSeed: "rn",
    },
    {
      id: "mem_ys",
      name: "Yusuf Saleh",
      title: "Data Scientist",
      role: "Member",
      timezone: "Europe/Berlin",
      avatarSeed: "ys",
    },
    {
      id: "mem_tm",
      name: "Talia Mendez",
      title: "Lifecycle Marketing",
      role: "Member",
      timezone: "America/Los_Angeles",
      avatarSeed: "tm",
    },
    {
      id: "mem_jp",
      name: "Jon Park",
      title: "Infra Engineer",
      role: "Member",
      timezone: "America/New_York",
      avatarSeed: "jp",
    },
  ],
  okrs: [
    {
      id: "okr_ns_1",
      teamId: "team_northstar",
      objective: "Make delivery boring (in the best way).",
      timeframe: "Q1 2026",
      ownerId: "mem_mc",
      tags: ["reliability", "release-train", "operations"],
      keyResults: [
        {
          id: "kr_ns_1_1",
          title: "Raise deploy success rate to 99.8%",
          ownerId: "mem_ad",
          unit: "percent",
          current: 99.2,
          target: 99.8,
          confidence: 0.74,
          sparkline: [98.9, 99.0, 99.1, 99.2, 99.2, 99.3, 99.2],
        },
        {
          id: "kr_ns_1_2",
          title: "Cut P1 incident count to <= 2 per month",
          ownerId: "mem_kl",
          unit: "count",
          current: 3,
          target: 2,
          confidence: 0.61,
          sparkline: [6, 5, 4, 4, 3, 3, 3],
        },
        {
          id: "kr_ns_1_3",
          title: "Increase on-call satisfaction to 8.5/10",
          ownerId: "mem_jo",
          unit: "score",
          current: 7.8,
          target: 8.5,
          confidence: 0.67,
          sparkline: [6.9, 7.2, 7.4, 7.6, 7.7, 7.8, 7.8],
        },
      ],
      checkIns: [
        {
          id: "ci_ns_1_a",
          at: "2026-01-19T16:00:00.000Z",
          authorId: "mem_mc",
          note:
            "Release train stabilized. Biggest drag is flaky end-to-end suite; reliability work is paying off.",
          confidence: 0.68,
        },
        {
          id: "ci_ns_1_b",
          at: "2026-02-05T16:00:00.000Z",
          authorId: "mem_ad",
          note:
            "Deploy success improved but P1 count stuck at 3. Root cause: two noisy dependencies. Mitigation in flight.",
          confidence: 0.63,
        },
      ],
    },
    {
      id: "okr_ns_2",
      teamId: "team_northstar",
      objective: "Turn operational debt into leverage.",
      timeframe: "Q1 2026",
      ownerId: "mem_am",
      tags: ["debt", "automation", "guardrails"],
      keyResults: [
        {
          id: "kr_ns_2_1",
          title: "Automate 12 recurring ops tasks",
          ownerId: "mem_jo",
          unit: "count",
          current: 8,
          target: 12,
          confidence: 0.77,
          sparkline: [2, 3, 4, 6, 7, 8, 8],
        },
        {
          id: "kr_ns_2_2",
          title: "Reduce alert noise by 35%",
          ownerId: "mem_ad",
          unit: "percent",
          current: 22,
          target: 35,
          confidence: 0.58,
          sparkline: [6, 9, 13, 15, 18, 20, 22],
        },
      ],
      checkIns: [
        {
          id: "ci_ns_2_a",
          at: "2026-02-01T17:00:00.000Z",
          authorId: "mem_am",
          note:
            "The automation backlog is clear. Biggest unblocker: unify runbooks and standardize templates.",
          confidence: 0.72,
        },
      ],
    },
    {
      id: "okr_or_1",
      teamId: "team_orbit",
      objective: "Double activation without doubling workload.",
      timeframe: "Q1 2026",
      ownerId: "mem_rn",
      tags: ["activation", "experiments", "onboarding"],
      keyResults: [
        {
          id: "kr_or_1_1",
          title: "Increase 7-day activation to 42%",
          ownerId: "mem_ys",
          unit: "percent",
          current: 34,
          target: 42,
          confidence: 0.66,
          sparkline: [29, 30, 31, 31, 32, 33, 34],
        },
        {
          id: "kr_or_1_2",
          title: "Ship 20 high-signal experiments",
          ownerId: "mem_tm",
          unit: "count",
          current: 14,
          target: 20,
          confidence: 0.71,
          sparkline: [5, 7, 9, 10, 12, 13, 14],
        },
        {
          id: "kr_or_1_3",
          title: "Improve onboarding clarity to 8.8/10",
          ownerId: "mem_si",
          unit: "score",
          current: 8.1,
          target: 8.8,
          confidence: 0.62,
          sparkline: [7.6, 7.8, 7.9, 8.0, 8.0, 8.1, 8.1],
        },
      ],
      checkIns: [
        {
          id: "ci_or_1_a",
          at: "2026-02-08T14:30:00.000Z",
          authorId: "mem_rn",
          note:
            "Activation is trending up. The friction now is 'first value' latency; we need a faster aha moment.",
          confidence: 0.67,
        },
      ],
    },
    {
      id: "okr_or_2",
      teamId: "team_orbit",
      objective: "Make growth learnings compounding.",
      timeframe: "Q1 2026",
      ownerId: "mem_am",
      tags: ["insights", "velocity", "instrumentation"],
      keyResults: [
        {
          id: "kr_or_2_1",
          title: "Reduce time-to-insight to 48 hours",
          ownerId: "mem_ys",
          unit: "score",
          current: 3.1,
          target: 4.0,
          confidence: 0.6,
          sparkline: [2.4, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1],
        },
        {
          id: "kr_or_2_2",
          title: "Increase experiment reuse rate to 30%",
          ownerId: "mem_tm",
          unit: "percent",
          current: 18,
          target: 30,
          confidence: 0.55,
          sparkline: [8, 9, 12, 13, 15, 16, 18],
        },
      ],
      checkIns: [],
    },
    {
      id: "okr_hb_1",
      teamId: "team_harbor",
      objective: "Build a platform teams trust blindly.",
      timeframe: "Q1 2026",
      ownerId: "mem_kl",
      tags: ["platform", "latency", "stability"],
      keyResults: [
        {
          id: "kr_hb_1_1",
          title: "Raise platform SLA to 99.95%",
          ownerId: "mem_jp",
          unit: "percent",
          current: 99.91,
          target: 99.95,
          confidence: 0.7,
          sparkline: [99.85, 99.87, 99.89, 99.90, 99.91, 99.91, 99.91],
        },
        {
          id: "kr_hb_1_2",
          title: "Cut p95 API latency to 220ms",
          ownerId: "mem_mc",
          unit: "score",
          current: 2.9,
          target: 4.0,
          confidence: 0.58,
          sparkline: [2.1, 2.2, 2.4, 2.6, 2.7, 2.8, 2.9],
        },
        {
          id: "kr_hb_1_3",
          title: "Migrate 6 critical services to new gateway",
          ownerId: "mem_kl",
          unit: "count",
          current: 4,
          target: 6,
          confidence: 0.64,
          sparkline: [1, 2, 2, 3, 3, 4, 4],
        },
      ],
      checkIns: [
        {
          id: "ci_hb_1_a",
          at: "2026-02-03T18:20:00.000Z",
          authorId: "mem_kl",
          note:
            "Gateway migrations accelerating. Latency work depends on one kernel tuning PR; risk is manageable.",
          confidence: 0.65,
        },
      ],
    },
  ],
  initiatives: [
    {
      id: "init_ns_1",
      teamId: "team_northstar",
      name: "Release Train 2.0",
      ownerId: "mem_mc",
      health: "AMBER",
      start: "2026-01-06T00:00:00.000Z",
      end: "2026-03-20T00:00:00.000Z",
      progress: 0.62,
      linkedProjectIds: ["proj_ns_1", "proj_ns_2"],
    },
    {
      id: "init_or_1",
      teamId: "team_orbit",
      name: "Activation Sprintline",
      ownerId: "mem_rn",
      health: "GREEN",
      start: "2026-01-10T00:00:00.000Z",
      end: "2026-03-14T00:00:00.000Z",
      progress: 0.58,
      linkedProjectIds: ["proj_or_1", "proj_or_3"],
    },
    {
      id: "init_hb_1",
      teamId: "team_harbor",
      name: "Gateway Cutover",
      ownerId: "mem_kl",
      health: "AMBER",
      start: "2026-01-03T00:00:00.000Z",
      end: "2026-03-29T00:00:00.000Z",
      progress: 0.66,
      linkedProjectIds: ["proj_hb_1", "proj_hb_2"],
    },
  ],
  projects: [
    {
      id: "proj_ns_1",
      teamId: "team_northstar",
      name: "E2E Stability Program",
      ownerId: "mem_ad",
      status: "Active",
      health: "AMBER",
      start: "2026-01-08T00:00:00.000Z",
      end: "2026-03-07T00:00:00.000Z",
      tags: ["testing", "quality"],
      milestones: [
        {
          id: "ms_ns_1",
          title: "Flake triage playbook",
          date: "2026-01-20T00:00:00.000Z",
          status: "Done",
          detail: "Top failure classes + owner routing.",
        },
        {
          id: "ms_ns_2",
          title: "Quarantine automation",
          date: "2026-02-18T00:00:00.000Z",
          status: "Next",
          detail: "Isolate flaky specs without blocking releases.",
        },
        {
          id: "ms_ns_3",
          title: "Parallelized pipeline",
          date: "2026-03-03T00:00:00.000Z",
          status: "Blocked",
          detail: "Needs runner capacity and cache hygiene.",
        },
      ],
      dependencies: [
        { projectId: "proj_hb_2", note: "Runner capacity improvements" },
      ],
      riskFlags: ["Runner saturation on peak days", "Cache invalidation storms"],
    },
    {
      id: "proj_ns_2",
      teamId: "team_northstar",
      name: "Alert Tuning: Noise to Signal",
      ownerId: "mem_jo",
      status: "Active",
      health: "GREEN",
      start: "2026-01-15T00:00:00.000Z",
      end: "2026-02-28T00:00:00.000Z",
      tags: ["observability"],
      milestones: [
        {
          id: "ms_ns2_1",
          title: "Pager budget policy",
          date: "2026-02-02T00:00:00.000Z",
          status: "Done",
          detail: "Define what deserves a wake-up.",
        },
        {
          id: "ms_ns2_2",
          title: "SLO dashboard revamp",
          date: "2026-02-21T00:00:00.000Z",
          status: "Next",
          detail: "SLOs that map to user pain, not internals.",
        },
      ],
      dependencies: [],
      riskFlags: [],
    },
    {
      id: "proj_or_1",
      teamId: "team_orbit",
      name: "Onboarding 2-Minute Aha",
      ownerId: "mem_si",
      status: "Active",
      health: "GREEN",
      start: "2026-01-12T00:00:00.000Z",
      end: "2026-03-10T00:00:00.000Z",
      tags: ["onboarding", "ux"],
      milestones: [
        {
          id: "ms_or_1",
          title: "First value map",
          date: "2026-01-22T00:00:00.000Z",
          status: "Done",
          detail: "Where users hesitate, where they flow.",
        },
        {
          id: "ms_or_2",
          title: "Frictionless setup",
          date: "2026-02-25T00:00:00.000Z",
          status: "Next",
          detail: "Defaults that feel personalized.",
        },
      ],
      dependencies: [{ projectId: "proj_hb_1", note: "Gateway endpoints for setup" }],
      riskFlags: ["Setup latency spikes on first-run"],
    },
    {
      id: "proj_or_3",
      teamId: "team_orbit",
      name: "Experiment Library",
      ownerId: "mem_ys",
      status: "Planning",
      health: "AMBER",
      start: "2026-02-17T00:00:00.000Z",
      end: "2026-03-30T00:00:00.000Z",
      tags: ["insights", "velocity"],
      milestones: [
        {
          id: "ms_or_3_1",
          title: "Taxonomy + tags",
          date: "2026-02-28T00:00:00.000Z",
          status: "Next",
          detail: "A library you can query in 20 seconds.",
        },
      ],
      dependencies: [],
      riskFlags: ["Instrumentation drift across platforms"],
    },
    {
      id: "proj_hb_1",
      teamId: "team_harbor",
      name: "Gateway v3: Cutover Plan",
      ownerId: "mem_kl",
      status: "Active",
      health: "AMBER",
      start: "2026-01-05T00:00:00.000Z",
      end: "2026-03-24T00:00:00.000Z",
      tags: ["gateway", "migration"],
      milestones: [
        {
          id: "ms_hb_1",
          title: "Traffic shadowing",
          date: "2026-02-10T00:00:00.000Z",
          status: "Done",
          detail: "Compare outputs silently in prod.",
        },
        {
          id: "ms_hb_2",
          title: "Canary to 10%",
          date: "2026-02-22T00:00:00.000Z",
          status: "Next",
          detail: "Progressive exposure with rollback hooks.",
        },
        {
          id: "ms_hb_3",
          title: "Cutover 100%",
          date: "2026-03-21T00:00:00.000Z",
          status: "Blocked",
          detail: "Waiting on one dependency contract.",
        },
      ],
      dependencies: [],
      riskFlags: ["Upstream contract mismatch", "Cold-start overhead"],
    },
    {
      id: "proj_hb_2",
      teamId: "team_harbor",
      name: "Build System: Runner Capacity",
      ownerId: "mem_jp",
      status: "Active",
      health: "GREEN",
      start: "2026-01-21T00:00:00.000Z",
      end: "2026-02-27T00:00:00.000Z",
      tags: ["ci", "infra"],
      milestones: [
        {
          id: "ms_hb2_1",
          title: "Autoscale policy",
          date: "2026-02-08T00:00:00.000Z",
          status: "Done",
          detail: "Scale with queue depth, not CPU.",
        },
        {
          id: "ms_hb2_2",
          title: "Warm pool",
          date: "2026-02-19T00:00:00.000Z",
          status: "Next",
          detail: "Avoid cold starts for bursty hours.",
        },
      ],
      dependencies: [],
      riskFlags: [],
    },
  ],
  signals: [
    {
      id: "sig_1",
      teamId: "team_northstar",
      type: "Blocker",
      title: "Flaky suite blocks release train",
      detail:
        "Parallelization is blocked until runner capacity is stabilized. Quarantine automation will cut impact quickly.",
      severity: 4,
      createdAt: "2026-02-11T12:00:00.000Z",
      related: { projectId: "proj_ns_1" },
    },
    {
      id: "sig_2",
      teamId: "team_orbit",
      type: "Win",
      title: "Activation +3pts after setup refresh",
      detail:
        "A smaller first-run surface increased completion. Next: reduce time-to-first-value with guided defaults.",
      severity: 2,
      createdAt: "2026-02-09T12:00:00.000Z",
      related: { okrId: "okr_or_1", projectId: "proj_or_1" },
    },
    {
      id: "sig_3",
      teamId: "team_harbor",
      type: "Risk",
      title: "Gateway contract mismatch risk at cutover",
      detail:
        "One upstream service returns ambiguous error codes. Contract test is pending; canary must include synthetic checks.",
      severity: 5,
      createdAt: "2026-02-06T12:00:00.000Z",
      related: { projectId: "proj_hb_1" },
    },
    {
      id: "sig_4",
      teamId: "team_orbit",
      type: "Risk",
      title: "Instrumentation drift reduces experiment reuse",
      detail:
        "Events vary across platforms. Standardize tracking and add validation to unblock the experiment library.",
      severity: 3,
      createdAt: "2026-02-12T12:00:00.000Z",
      related: { projectId: "proj_or_3" },
    },
  ],
  series: [
    {
      id: "ser_ns_velocity",
      teamId: "team_northstar",
      label: "Delivery Health",
      unit: "score",
      points: [
        { t: "2026-01-01T00:00:00.000Z", v: 6.4 },
        { t: "2026-01-08T00:00:00.000Z", v: 6.8 },
        { t: "2026-01-15T00:00:00.000Z", v: 7.1 },
        { t: "2026-01-22T00:00:00.000Z", v: 7.0 },
        { t: "2026-01-29T00:00:00.000Z", v: 7.3 },
        { t: "2026-02-05T00:00:00.000Z", v: 7.4 },
        { t: "2026-02-12T00:00:00.000Z", v: 7.6 },
      ],
    },
    {
      id: "ser_or_activation",
      teamId: "team_orbit",
      label: "Activation (7d)",
      unit: "percent",
      points: [
        { t: "2026-01-01T00:00:00.000Z", v: 28 },
        { t: "2026-01-08T00:00:00.000Z", v: 29 },
        { t: "2026-01-15T00:00:00.000Z", v: 30 },
        { t: "2026-01-22T00:00:00.000Z", v: 31 },
        { t: "2026-01-29T00:00:00.000Z", v: 32 },
        { t: "2026-02-05T00:00:00.000Z", v: 33 },
        { t: "2026-02-12T00:00:00.000Z", v: 34 },
      ],
    },
    {
      id: "ser_hb_latency",
      teamId: "team_harbor",
      label: "Platform Stability",
      unit: "score",
      points: [
        { t: "2026-01-01T00:00:00.000Z", v: 6.8 },
        { t: "2026-01-08T00:00:00.000Z", v: 6.9 },
        { t: "2026-01-15T00:00:00.000Z", v: 7.0 },
        { t: "2026-01-22T00:00:00.000Z", v: 7.1 },
        { t: "2026-01-29T00:00:00.000Z", v: 7.2 },
        { t: "2026-02-05T00:00:00.000Z", v: 7.4 },
        { t: "2026-02-12T00:00:00.000Z", v: 7.5 },
      ],
    },
  ],
  rituals: [
    {
      id: "rit_ns_1",
      teamId: "team_northstar",
      title: "Ops Review",
      cadence: "Weekly",
      day: "Tue",
      timeUtc: "17:00",
      ownerId: "mem_am",
    },
    {
      id: "rit_or_1",
      teamId: "team_orbit",
      title: "Growth Standup",
      cadence: "Weekly",
      day: "Mon",
      timeUtc: "16:30",
      ownerId: "mem_rn",
    },
    {
      id: "rit_hb_1",
      teamId: "team_harbor",
      title: "Platform Change Council",
      cadence: "Biweekly",
      day: "Thu",
      timeUtc: "18:00",
      ownerId: "mem_mc",
    },
  ],
};

