"use client";

import { ExternalLink, RefreshCcw, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Pill } from "@/components/ui/pill";
import { usePaddle } from "@/components/billing/paddle-provider";
import { TrackedLink } from "@/components/telemetry/tracked-link";

function compactTransactionId(value: string): string {
  if (value.length <= 18) {
    return value;
  }
  return `${value.slice(0, 10)}...${value.slice(-6)}`;
}

export function PaymentLinkClient(props: { transactionId: string | null }) {
  const { configured, ready, openCheckout } = usePaddle();
  const hasTransaction = Boolean(props.transactionId);
  const canRetry = configured && ready && Boolean(props.transactionId);

  return (
    <div className="pb-12 pt-10 md:pb-16 md:pt-14">
      <Pill tone="accent">Secure checkout</Pill>
      <h1 className="mt-4 max-w-[12ch] text-balance font-[family-name:var(--font-kw-display)] text-5xl leading-[0.95] tracking-tight text-[color:var(--kw-ink)] sm:text-6xl">
        Paddle payment links for Hifzer.
      </h1>
      <p className="mt-4 max-w-2xl text-sm leading-7 text-[color:var(--kw-muted)]">
        This page is reserved for secure Hifzer checkout links generated by Paddle. When a valid
        payment transaction is attached, Paddle should open the checkout overlay automatically.
      </p>

      <Card className="mt-8">
        <div className="flex items-start gap-3">
          <span className="grid h-11 w-11 place-items-center rounded-2xl border border-[color:var(--kw-border-2)] bg-white/70 text-[color:var(--kw-ink-2)] shadow-[var(--kw-shadow-soft)]">
            <ShieldCheck size={18} />
          </span>
          <div className="min-w-0">
            <p className="text-sm font-semibold text-[color:var(--kw-ink)]">
              {hasTransaction ? "Payment link ready" : "Waiting for a Paddle payment link"}
            </p>
            <p className="mt-1 text-sm leading-7 text-[color:var(--kw-muted)]">
              {hasTransaction
                ? "If the overlay did not appear automatically, you can reopen it using the button below."
                : "Open this page using a Paddle-generated payment link or a Hifzer checkout flow that includes a valid transaction."}
            </p>
            {hasTransaction ? (
              <p className="mt-3 text-xs font-semibold uppercase tracking-[0.16em] text-[color:var(--kw-faint)]">
                Transaction {compactTransactionId(props.transactionId!)}
              </p>
            ) : null}
          </div>
        </div>

        <div className="mt-5 flex flex-wrap items-center gap-2">
          {hasTransaction ? (
            <Button
              className="gap-2"
              disabled={!canRetry}
              onClick={() => {
                if (!props.transactionId) {
                  return;
                }
                openCheckout({ transactionId: props.transactionId });
              }}
            >
              Reopen checkout <RefreshCcw size={16} />
            </Button>
          ) : null}

          <Button asChild variant="secondary">
            <TrackedLink href="/" telemetryName="payment-link.back-home">
              Back to Hifzer
            </TrackedLink>
          </Button>

          <Button asChild variant="ghost">
            <TrackedLink href="/support" telemetryName="payment-link.support">
              Support page <ExternalLink size={16} />
            </TrackedLink>
          </Button>
        </div>

        {hasTransaction && !configured ? (
          <p className="mt-4 text-sm leading-7 text-[color:var(--kw-muted)]">
            Paddle client settings are not configured for this environment yet, so the overlay
            cannot open from this page.
          </p>
        ) : null}

        {hasTransaction && configured && !ready ? (
          <p className="mt-4 text-sm leading-7 text-[color:var(--kw-muted)]">
            Loading secure checkout...
          </p>
        ) : null}
      </Card>
    </div>
  );
}
